### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by ceased18** [Vincenth421/OW-PUGS-Matchmaker#3]
Hello, I downloaded the files but I cannot get the program to work. 
Here is the error code:
Traceback (most recent call last):
  File "d:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master\bot.py", line 4, in <module>
    from bot_data_functions import *
  File "d:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master\bot_data_functions.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
PS D:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master>

**Comment by ceased18** [comment]
Sorry I ended up installing Numpy. Here is the new issue:

PS D:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master> & C:/Users/ishra/AppData/Local/Programs/Python/Python39/python.exe "d:/Discord Ladder Bot/OW Matchmaker PUGS/OW-PUGS-Matchmaker-master/multirole_queue.py"
  File "d:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master\multirole_queue.py", line 41
    if roles != "000"
                     ^
SyntaxError: invalid syntax
PS D:\Discord Ladder Bot\OW Matchmaker PUGS\OW-PUGS-Matchmaker-master>

**Comment by Vincenth421** [comment]
Hi, I just fixed it. Download the file again and have a try, thanks :)

**Comment by ceased18** [comment]
Am I doing something wrong? Here is the new issue I got.

PS D:\Discord Ladder Bot\OW-PUGS-Matchmaker-master> & C:/Users/ishra/AppData/Local/Programs/Python/Python39/python.exe "d:/Discord Ladder Bot/OW-PUGS-Matchmaker-master/bot.py"
Traceback (most recent call last):
  File "d:\Discord Ladder Bot\OW-PUGS-Matchmaker-master\bot.py", line 4, in <module>
    from bot_data_functions import *
  File "d:\Discord Ladder Bot\OW-PUGS-Matchmaker-master\bot_data_functions.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS D:\Discord Ladder Bot\OW-PUGS-Matchmaker-master> 

If you can help me on discord: %ishrak#7429

**Comment by ceased18** [comment]
Thank you so much, no issues so far

**Comment by Vincenth421** [comment]
Great, thanks for using our bot

**Comment by ceased18** [comment]
Hello,
What level of python do you think I would need in order to add more
features to the bot?

**Comment by cholland4** [comment]
What kind of features are you thinking? Our background in making this bot is mainly self-taught, so you can likely find materials online to add the feature you want. I've also been considering coming back to this and updating it, so if you let me know what features you're interested, I can look into adding them.

**Comment by ceased18** [comment]
Hey,
I actually wanted to make this into a project where amateur Overwatch
players could join a discord server and then use the bot to q games.
So I think the competitive ladder in Overwatch is pretty terrible with
people trolling and throwing games so creating a competitive environment
like FACEIT with the bot could be cool.
If you guys are interested in helping with something like that, message me
on discord: %ishrak#7429

I actually have a couple of friends i'm doing this with and so far they
said:
- A preferred role feature for players so you can q that role immediately
when you use the command. So if you used .q it would q that preferred role
unless you specify
Or, i don't even know if this would be possible but if somewhere in the
discord you could react to a message that would give you a role,
dps/supp/tank/fill, so when you hit .q the bot recognizes your role and
automatically q's you for that
- If the roles command could also be activated by typing .queuecheck/.qc
- You can q each of the roles individually or fill, but the bot
doesnt allow you to q for two roles at once, like dps and support for
example
-  If .leavequeue/.lq could do what .leave/.l does just because its a bit
clearer
- A system for opponent confirming match score after one team submits it
- A system for tracking player win/loss with a command that brings it up
- In correspondence with that, a simple elo system to start, players gain
+20 for a win and lose -10 for a loss, and a top leaderboard of all
documented players off of that
- For the maps, if there could be a system where 3 random maps from the
competitive pool could be chosen, and then each player could vote for which
map they want to play, through discord dm, channel, or reaction
- If the map could DM everyone when the match starts a list of the BNETs
for everyone in the lobby, or just leave a message like that in a channel
so everyone can see (second one prob easier and better)
- When the q starts, if there could be a ready up option in like 60s,
unreadied players get kicked from q
- Ability to group up with people in q so that they get placed on the same
team when teams are automated
- When people hop into q, groups should ideally be matchmade with other
groups

- I don't even know if this is implementable but an SR balancing
system/algorithm from the Q for the teams so that the games r balanced
give one team the highest and lowest sr on a role, then the other team gets
the highest and lowest for the next role, then the original team gets the
highest and lowest for the last role

Sorry, that's a lot to pile on you but we've just done a lot of
brainstorming and thinking and are super excited about the idea especially
with OW 2 beta releasing near the end of this month I think this could make
a huge impact on the amateur scene.
If you could point out resources I could use to try and learn how to
implement these that would be great as well, thank you so much I appreciate
the work you put into the project and for reaching out.

Best,
Ishrak
